language: python

before_install:
    - sudo apt-get update -qq
    - sudo apt-get install -qq libopenobex1-dev

install:
    - pip install pybluez
    - pip install PyOBEX
    - hg clone https://bitbucket.org/dboddie/pyobex
    - cd pyobex; ./setup.py install
    - cd ..

script: nosetests

notification:
    email:
        - eliasj@student.chalmers.se
