language: python

before_install:
    - sudo apt-get update -qq
    - sudo apt-get install -qq libopenobex1-dev

install:
    - pip install pybluez
    - hg clone ssh://hg@bitbucket.org/dboddie/pyobex
    - python pyobex/setup.py install

script: nosetests

notification:
    email:
        - eliasj@student.chalmers.se
